# Generated by Django 4.2.18 on 2025-02-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boleto",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("government_id", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("debt_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("debt_due_date", models.DateField()),
                (
                    "boleto_gerado",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "email_enviado",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
