# Generated by Django 4.2.18 on 2025-02-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boletos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boleto",
            name="boleto_gerado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="email_enviado",
            field=models.BooleanField(default=False),
        ),
    ]
